# Generated by Django 6.0.6 on 2026-06-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('power', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitor_sen_timesta_4b6842_idx'), models.Index(fields=['is_anomaly'], name='monitor_sen_is_anom_17b3a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('severity', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3)),
                ('root_cause', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('full_diagnosis', models.JSONField(blank=True, null=True)),
                ('diagnosis_pending', models.BooleanField(default=True)),
                ('agent_iterations', models.IntegerField(default=0)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_logs', to='monitor.sensorreading')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitor_ano_timesta_f63866_idx'), models.Index(fields=['severity'], name='monitor_ano_severit_6cf076_idx')],
            },
        ),
    ]
