# Generated by Django 6.0.6 on 2026-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalylog',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
